### ISSUE TITLE
Latex

### ISSUE THREAD

**Issue by rivillon** [mon-oral/www.mon-oral.net#46]
Bonjour Laurent, est-il envisageable ou prévu à moyen terme de pouvoir intégrer du langage Tex dans les questions posées aux élèves dans les activités ou entraînements ? Je t'imagine débordé donc c'est une simple question.
Merci à toi

**Comment by laurentabbal** [comment]
Je devrais pouvoir ajouter MathJax dans la semaine.

**Comment by rivillon** [comment]
Merci beaucoup. Belle journée. Sébastien
