### ISSUE TITLE
Problème de fichier 

### ISSUE THREAD

**Issue by cagnola** [mon-oral/www.mon-oral.net#51]
Bonjour, 
Mes élèves ont utilisé mon-oral.net ce matin pour une activité (code: NTE2N3JY). 
Problème : sur 25 fichiers, je ne peux écouter 18 d'entre eux dans le lecteur intégré (0:00/0:00). 
J'ai toutefois réussi à télécharger un par un les fichiers, mais le fichier son n'inclut pas le nom de l'élève qui s'est enregistré. 
Y-a-t'il un moyen pour rétablir l'identité associée à chaque fichier? ou de rendre le fichier accessible via le lecteur intégré?
Merci de votre aide !
Cordialement,
Caroline Agnola

**Comment by laurentabbal** [comment]
Bonjour,
Je viens de tester l'activité. Les enregistrements et les lecteurs fonctionnent correctement.
Parfois, quand il y a de nombreux enregistrements, le chargement des lecteurs peut prendre quelques seconde (surtout si la machine ou le réseau a peu de ressources). Si tous les lecteurs ne se chargent pas, rafraichissez la page.

**Comment by cagnola** [comment]
Bonjour et merci beaucoup de votre réponse. 
Avant de vous contacter, j'avais bel et bien rafraîchi la page et essayé sur différents PC (ainsi que mon téléphone) et le même problème se posait à chaque fois... toujours en utilisant Firefox.  
Je viens de tester en utilisant un autre navigateur et là, effectivement, tous les lecteurs fonctionnent parfaitement sous Chromium. Me voilà soulagée car c'est vraiment une bonne application! 
Bonne fin de journée à vous.
