### ISSUE TITLE
disparition compte-rendus

### ISSUE THREAD

**Issue by antocasu** [mon-oral/www.mon-oral.net#53]
A plusieurs reprises, j'ai eu la mauvaise surprise d'avoir "perdu" des compte-rendus d'activité : en cliquant sur _[afficher / imprimer tous les comptes-rendus]_, j'ai pu constater que la liste était incomplète car bon nombre de CR avaient disparu ! 
Alors que je les avais bel et bien enregistrés !

Est-ce un problème lié au navigateur ? J'utilise Firefox, toujours mis à jour !

Antonello CASU
Prof. d'Italien

**Comment by laurentabbal** [comment]
Bonjour,
Il n'y a pas de raison pour que des comptes rendus disparaissent. C'est la première fois que cette situation est signalée.
Vous parlez de comptes rendus écrits ?
Avez-vous bien cliqué sur "sauvegarder les modifications" pour chaque compte rendu ?
