### ISSUE TITLE
Bogue sur les notes vocales

### ISSUE THREAD

**Issue by MNRIMBOUD** [mon-oral/www.mon-oral.net#69]
Sur mon-oral.net; quand je réécoute la note de commentaire que je souhaite laisser à un élève, c'est celle d'un autre professeur que j'entends.

**Comment by laurentabbal** [comment]
Oula! Pouvez-vous m'envoyer le code de l'enregistrement et me dire dans quelles circonstances il a été fait (QR code, une seule prise, plusieurs tentatives...) à contact@mon-oral.net
